name: Delete workflow runs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  del_runs:
    name: Delete workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
         delete_releases: true
         releases_keep_latest: 1
         delete_workflows: true
         workflows_keep_day: 1
         gh_token: ${{ secrets.GH_TOKEN }}
